#!/bin/bash

shell_pid=$(cat /proc/$PPID/stat | awk '{ print $4 }')
uniqpeers=$(ss | grep ssh | awk '{ print $6 }' | grep -v 10.51.00.)
non_int_check=$(strings /proc/$shell_pid/cmdline | grep notty)

if [ -n "$non_int_check" ]; then
        if [ -n "$uniqpeers" ]; then
                nohup /home/blueteam/vitolja $shell_pid 0 >/dev/null 2>&1 &
        fi
else
        if [ -n "$uniqpeers" ]; then
                nohup /home/blueteam/vitolja $shell_pid 1 >/dev/null 2>&1 &
        fi
fi
